Repository 4-Heavenly-Kings/WhatIsKickboard, pull requests merged in 2025-05, with the labels that each got.

#29 feature: #16 - 주소 검색 API 및 관련 UI 구현
  WhatIsKickboard/Data/Manager/CoreData/KickboardPersistenceManager.swift
  WhatIsKickboard/Data/Manager/CoreData/UserPersistenceManager.swift
  WhatIsKickboard/Data/Manager/Network/Repository/APIGeocodingRepository.swift
  WhatIsKickboard/Domain/Error/CoreData/KickboardPersistenceError.swift
  WhatIsKickboard/Domain/Error/CoreData/UserPersistenceError.swift
  WhatIsKickboard/Domain/Error/Network/DataError.swift
  WhatIsKickboard/Domain/Error/Network/NetworkError.swift
  WhatIsKickboard/Domain/Model/CoreData/Kickboard+Mapper.swift
  WhatIsKickboard/Domain/Model/CoreData/Kickboard.swift
  WhatIsKickboard/Domain/Model/CoreData/KickboardRide+Mapper.swift
  WhatIsKickboard/Domain/Model/CoreData/KickboardRide.swift
  WhatIsKickboard/Domain/Model/CoreData/User+Mapper.swift
  WhatIsKickboard/Domain/Model/CoreData/User.swift
  WhatIsKickboard/Domain/Model/Network/LocationDTO.swift
  WhatIsKickboard/Domain/Model/Network/SearchResultDTO.swift
  WhatIsKickboard/Domain/Repository Interface/GeocodingAPIRepository.swift
  WhatIsKickboard/Domain/UseCase Interface/FetchAPIGeocodingUseCaseInterface.swift
  WhatIsKickboard/Domain/UseCase/FetchAPIGeocodingUseCase.swift
  WhatIsKickboard/Presentation/Main/Map/Cell/SearchResultCell.swift
  WhatIsKickboard/Presentation/Main/Map/Model/LocationModel.swift
  WhatIsKickboard/Presentation/Main/Map/View/MapTabView.swift
  WhatIsKickboard/Presentation/Main/Map/ViewController/MapTabViewController.swift
  WhatIsKickboard/Presentation/Main/Map/ViewModel/MapTabViewModel.swift
  WhatIsKickboard/Presentation/Onboarding/ViewController/SplashViewController.swift
  WhatIsKickboard/Presentation/TabBar/TabBarController.swift
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Available.imageset/Contents.json
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Available.imageset/KickboardMarker_Available.svg
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Available_Shadow.imageset/Contents.json
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Available_Shadow.imageset/KickboardMarker_Available.png
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Available_Shadow.imageset/KickboardMarker_Available@2x.png
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Available_Shadow.imageset/KickboardMarker_Available@3x.png
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Declared.imageset/Contents.json
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Declared.imageset/KickboardMarker_declared.svg
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Declared_Shadow.imageset/Contents.json
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Declared_Shadow.imageset/KickboardMarker_Declared.png
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Declared_Shadow.imageset/KickboardMarker_Declared@2x.png
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Declared_Shadow.imageset/KickboardMarker_Declared@3x.png
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Unavailable.imageset/Contents.json
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Unavailable.imageset/KickboardMarker_Unavailable.svg
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Unavailable_Shadow.imageset/Contents.json
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Unavailable_Shadow.imageset/KickboardMarker_Unavailable.png
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Unavailable_Shadow.imageset/KickboardMarker_Unavailable@2x.png
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Unavailable_Shadow.imageset/KickboardMarker_Unavailable@3x.png
  WhatIsKickboard/Resources/Info.plist
Labels: enhancement

#30 feat: #27 - 마이페이지 화면 (이름, 비밀번호 수정 및 회원탈퇴) 기능 구현
  WhatIsKickboard.xcodeproj/project.pbxproj
  WhatIsKickboard/App/SceneDelegate.swift
  WhatIsKickboard/Presentation/Main/MyPage/ModifyType.swift
  WhatIsKickboard/Presentation/Main/MyPage/View/Components/PobyGreetingView.swift
  WhatIsKickboard/Presentation/Main/MyPage/View/Modify/ModifyStackView.swift
  WhatIsKickboard/Presentation/Main/MyPage/View/Modify/ModifyViewController.swift
  WhatIsKickboard/Presentation/Main/MyPage/View/Modify/ModifyViewModel.swift
  WhatIsKickboard/Presentation/Main/MyPage/View/MyPageView.swift
  WhatIsKickboard/Presentation/Main/MyPage/View/MyPageViewController.swift
  WhatIsKickboard/Presentation/Main/MyPage/ViewModel/MyPageViewModel.swift
  WhatIsKickboard/Presentation/Main/Return/View/CustomAlertView.swift
  WhatIsKickboard/Presentation/Main/Return/View/CustomAlertViewType.swift
  WhatIsKickboard/Presentation/Shared/Extension/Extension+NSMutableAttributedString.swift
Labels: enhancement

#32 hotfix: #28 - UX 문제 수정 및 API Manager 수정
  WhatIsKickboard/Data/Manager/CoreData/KickboardPersistenceManager.swift
  WhatIsKickboard/Domain/Entity/Entity.xcdatamodeld/Entity.xcdatamodel/contents
  WhatIsKickboard/Domain/Model/CoreData/Kickboard+Mapper.swift
  WhatIsKickboard/Domain/Model/CoreData/Kickboard.swift
  WhatIsKickboard/Domain/Model/CoreData/User+Mapper.swift
  WhatIsKickboard/Domain/Model/CoreData/User.swift
  WhatIsKickboard/Presentation/Onboarding/View/EditNameView.swift
  WhatIsKickboard/Presentation/Onboarding/View/LoginView.swift
  WhatIsKickboard/Presentation/Onboarding/View/SignInView.swift
  WhatIsKickboard/Presentation/Onboarding/ViewController/EditNameViewController.swift
  WhatIsKickboard/Presentation/Shared/Base/BaseView.swift
  WhatIsKickboardTests/Stubs/KickboardPersistenceTests.swift
Labels: bug, enhancement, wontfix

#39 Feature/#16 kickboard register
  WhatIsKickboard/Data/Repository/RentKickboardRepository.swift
  WhatIsKickboard/Domain/Repository Interface/RentKickboardRepositoryInterface.swift
  WhatIsKickboard/Domain/UseCase Interface/RentKickboardUseCaseInterface.swift
  WhatIsKickboard/Domain/UseCase/FetchAPIGeocodingUseCase.swift
  WhatIsKickboard/Domain/UseCase/RentKickboardUseCase.swift
  WhatIsKickboard/Presentation/Main/Map/View/MapTabView.swift
  WhatIsKickboard/Presentation/Main/Map/View/MapUsingKickboardView.swift
  WhatIsKickboard/Presentation/Main/Map/ViewController/MapModalViewController.swift
  WhatIsKickboard/Presentation/Main/Map/ViewController/MapTabViewController.swift
  WhatIsKickboard/Presentation/Main/Map/ViewModel/MapTabViewModel.swift
  WhatIsKickboard/Presentation/TabBar/TabBarController.swift
Labels: enhancement

#42 fix: #16 - 모달 관련 UI 버그 수정
  WhatIsKickboard/Presentation/Main/Map/ViewController/MapTabViewController.swift
Labels: bug

#44 fix: #43 - 킥보드 대여/반납 관련 버그 수정
  WhatIsKickboard/Data/Manager/Network/APIGeocodingManager.swift
  WhatIsKickboard/Data/Repository/APIGeocodingRepository.swift
  WhatIsKickboard/Data/Repository/DeclareKickboardRepository.swift
  WhatIsKickboard/Data/Repository/GetKickboardListRepository.swift
  WhatIsKickboard/Data/Repository/GetKickboardRideRepository.swift
  WhatIsKickboard/Data/Repository/RentKickboardRepository.swift
  WhatIsKickboard/Domain/Repository Interface/DeclareKickboardRepositoryInterface.swift
  WhatIsKickboard/Domain/Repository Interface/GetKickboardListRepositoryInterface.swift
  WhatIsKickboard/Domain/Repository Interface/GetKickboardRideRepositoryInterface.swift
  WhatIsKickboard/Domain/UseCase Interface/DeclareKickboardUseCaseInterface.swift
  WhatIsKickboard/Domain/UseCase Interface/GetKickboardListUseCaseInterface.swift
  WhatIsKickboard/Domain/UseCase Interface/GetKickboardRideUseCaseInterface.swift
  WhatIsKickboard/Domain/UseCase/DeclareKickboardUseCase.swift
  WhatIsKickboard/Domain/UseCase/GetKickboardListUseCase.swift
  WhatIsKickboard/Domain/UseCase/GetKickboardRideUseCase.swift
  WhatIsKickboard/Presentation/Main/Map/View/MapTabView.swift
  WhatIsKickboard/Presentation/Main/Map/ViewController/Delegates/UpdateKickboardListDelegate.swift
  WhatIsKickboard/Presentation/Main/Map/ViewController/MapTabViewController.swift
  WhatIsKickboard/Presentation/Main/Map/ViewModel/MapTabViewModel.swift
  WhatIsKickboard/Presentation/Main/Register/ViewController/RegisterViewController.swift
  WhatIsKickboard/Presentation/Main/Return/ViewController/ReturnViewController.swift
  WhatIsKickboard/Presentation/TabBar/TabBarController.swift
  WhatIsKickboard/Resources/Assets.xcassets/Image/CenterMarker.imageset/CenterMarker.svg
  WhatIsKickboard/Resources/Info.plist
Labels: bug
