Repository 4-Heavenly-Kings/WhatIsKickboard, pull requests merged in 2025-04, with the labels that each got.

#6 feat: #1, #5 - CoreData DTO 구조 설계 및 API Manager 구현
  WhatIsKickboard.xcodeproj/project.pbxproj
  WhatIsKickboard.xcodeproj/xcshareddata/xcschemes/WhatIsKickboard.xcscheme
  WhatIsKickboard/Data/Core/BaseCoreDataManager.swift
  WhatIsKickboard/Data/Core/CoreDataStack.swift
  WhatIsKickboard/Data/Empty1.swift
  WhatIsKickboard/Data/Manager/KickboardPersistenceManager.swift
  WhatIsKickboard/Data/Manager/UserPersistenceManager.swift
  WhatIsKickboard/Domain/Empty2.swift
  WhatIsKickboard/Domain/Entity/Entity.xcdatamodeld/Entity.xcdatamodel/contents
  WhatIsKickboard/Domain/Error/KickboardPersistenceError.swift
  WhatIsKickboard/Domain/Error/UserPersistenceError.swift
  WhatIsKickboard/Domain/Model/Kickboard+Mapper.swift
  WhatIsKickboard/Domain/Model/Kickboard.swift
  WhatIsKickboard/Domain/Model/KickboardRide+Mapper.swift
  WhatIsKickboard/Domain/Model/KickboardRide.swift
  WhatIsKickboard/Domain/Model/User+Mapper.swift
  WhatIsKickboard/Domain/Model/User.swift
  WhatIsKickboard/Resources/Assets.xcassets/Color/coreColor.colorset/Contents.json
  WhatIsKickboardTests/Mock/Kickboard.swift
  WhatIsKickboardTests/Mock/Ride.swift
  WhatIsKickboardTests/Mock/User.swift
  WhatIsKickboardTests/Stubs/KickboardPersistenceTests.swift
  WhatIsKickboardTests/Stubs/UserPersistenceTests.swift
  WhatIsKickboardTests/WhatIsKickboardTests.swift
Labels: documentation, enhancement, test

#9 hotfix: 빠른 변경 사항을 위한 PR
  WhatIsKickboard/Data/Mock/Kickboard+Mock.swift
  WhatIsKickboard/Data/Mock/KickboardRide+Mock.swift
  WhatIsKickboard/Data/Mock/User+Mock.swift
  WhatIsKickboard/Presentation/Shared/Extension/Extension+UIFont.swift
Labels: enhancement, wontfix

#13 feat: #7 - Onboarding UI 구현
  WhatIsKickboard/Presentation/Onboarding/Login/LoginViewController.swift
  WhatIsKickboard/Presentation/Onboarding/Name/NameViewController.swift
  WhatIsKickboard/Presentation/Onboarding/SignUp/SignUpViewController.swift
  WhatIsKickboard/Presentation/Onboarding/View/EditNameView.swift
  WhatIsKickboard/Presentation/Onboarding/View/LoginView.swift
  WhatIsKickboard/Presentation/Onboarding/View/SignInView.swift
  WhatIsKickboard/Presentation/Onboarding/View/SplashView.swift
  WhatIsKickboard/Presentation/Onboarding/ViewController/EditNameViewController.swift
  WhatIsKickboard/Presentation/Onboarding/ViewController/LoginViewController.swift
  WhatIsKickboard/Presentation/Onboarding/ViewController/SignInViewController.swift
  WhatIsKickboard/Presentation/Onboarding/ViewController/SplashViewController.swift
Labels: enhancement

#14 feat: #3 - 지도 표시 및 현재 위치 이동 기능 구현
  WhatIsKickboard/Data/Mock/Kickboard+Mock.swift
  WhatIsKickboard/Domain/Utils/KickboardStatus.swift
  WhatIsKickboard/Presentation/Main/Map/View/MapTabView.swift
  WhatIsKickboard/Presentation/Main/Map/View/MapView.swift
  WhatIsKickboard/Presentation/Main/Map/ViewController/MapTabViewController.swift
  WhatIsKickboard/Presentation/Main/Map/ViewController/MapViewController.swift
  WhatIsKickboard/Presentation/Main/Map/ViewModel/MapTabViewModel.swift
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Available.imageset/Contents.json
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Available.imageset/KickboardMarker_Available.svg
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Declared.imageset/Contents.json
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Declared.imageset/KickboardMarker_declared.svg
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Unavailable.imageset/Contents.json
  WhatIsKickboard/Resources/Assets.xcassets/Image/KickboardMarker_Unavailable.imageset/KickboardMarker_Unavailable.svg
  WhatIsKickboard/Resources/Assets.xcassets/Image/LocationButton.imageset/Contents.json
  WhatIsKickboard/Resources/Assets.xcassets/Image/LocationButton.imageset/userLocation.svg
  WhatIsKickboard/Resources/Info.plist
Labels: enhancement

#20 hotfix - #18 Persistence Manager 반환 데이터 타입 변경
  WhatIsKickboard/Data/Manager/KickboardPersistenceManager.swift
  WhatIsKickboard/Data/Manager/UserPersistenceManager.swift
Labels: enhancement, wontfix

#21 feat: #16 - 킥보드 위치 등록 화면전환 로직 구현
  WhatIsKickboard/Data/Mock/Kickboard+Mock.swift
  WhatIsKickboard/Presentation/Main/Map/View/MapTabView.swift
  WhatIsKickboard/Presentation/Main/Map/ViewController/MapTabViewController.swift
  WhatIsKickboard/Presentation/Main/Map/ViewModel/MapTabViewModel.swift
  WhatIsKickboard/Presentation/TabBar/Delegates/ChangeSelectedIndexDelegate.swift
  WhatIsKickboard/Presentation/TabBar/TabBarController.swift
Labels: enhancement

#23 hotfix - #22 탑승정보 조희 API Manager 추가
  WhatIsKickboard/Data/Manager/KickboardPersistenceManager.swift
  WhatIsKickboard/Data/Mock/KickboardRide+Mock.swift
  WhatIsKickboard/Domain/Entity/Entity.xcdatamodeld/Entity.xcdatamodel/contents
  WhatIsKickboard/Domain/Model/KickboardRide+Mapper.swift
  WhatIsKickboard/Domain/Model/KickboardRide.swift
  WhatIsKickboardTests/Stubs/KickboardPersistenceTests.swift
  WhatIsKickboardTests/Stubs/UserPersistenceTests.swift
Labels: enhancement, wontfix, test

#24 hotfix: #22 - 킥보드 정보 address 필드 추가
  WhatIsKickboard/Data/Manager/KickboardPersistenceManager.swift
  WhatIsKickboard/Data/Mock/Kickboard+Mock.swift
  WhatIsKickboard/Domain/Entity/Entity.xcdatamodeld/Entity.xcdatamodel/contents
  WhatIsKickboard/Domain/Model/Kickboard+Mapper.swift
  WhatIsKickboard/Domain/Model/Kickboard.swift
  WhatIsKickboard/Presentation/Main/Map/ViewModel/MapTabViewModel.swift
  WhatIsKickboardTests/Stubs/KickboardPersistenceTests.swift
Labels: enhancement, wontfix, test

#26 feature: #15 - 온보딩 관련 UI 데이터 바인딩 및 ViewModel 구현
  WhatIsKickboard.xcodeproj/project.pbxproj
  WhatIsKickboard/App/SceneDelegate.swift
  WhatIsKickboard/Domain/Error/UserPersistenceError.swift
  WhatIsKickboard/Presentation/Main/Return/View/CustomAlertView.swift
  WhatIsKickboard/Presentation/Main/Return/View/CustomAlertViewType.swift
  WhatIsKickboard/Presentation/Onboarding/View/EditNameView.swift
  WhatIsKickboard/Presentation/Onboarding/View/LoginView.swift
  WhatIsKickboard/Presentation/Onboarding/View/SignInView.swift
  WhatIsKickboard/Presentation/Onboarding/ViewController/EditNameViewController.swift
  WhatIsKickboard/Presentation/Onboarding/ViewController/LoginViewController.swift
  WhatIsKickboard/Presentation/Onboarding/ViewController/SignInViewController.swift
  WhatIsKickboard/Presentation/Onboarding/ViewController/SplashViewController.swift
  WhatIsKickboard/Presentation/Onboarding/ViewModel/EditNameViewModel.swift
  WhatIsKickboard/Presentation/Onboarding/ViewModel/LoginViewModel.swift
  WhatIsKickboard/Presentation/Onboarding/ViewModel/SignInViewModel.swift
  WhatIsKickboard/Presentation/TabBar/TabBarController.swift
  WhatIsKickboard/Presentation/TabBar/ViewModel/TabbarViewModel.swift
Labels: enhancement, wontfix, test
